require('dotenv').config();

module.exports = {
  apps: [
    {
      name: "peasydeal_web",
      script: "npm",
      watch: true,
      args: "start",
      env: {
        "PORT": process.env.PORT,
        "DOMAIN": process.env.DOMAIN,
        "NODE_ENV": "development",
        "DATABASE_URL": process.env.DATABASE_URL,
        "SESSION_SECRET": process.env.SESSION_SECRET,
        "MYFB_ENDPOINT": process.env.MYFB_ENDPOINT,
        "PEASY_DEAL_ENDPOINT": process.env.PEASY_DEAL_ENDPOINT,
        "PAYPAL_CLIENT_ID": process.env.PAYPAL_CLIENT_ID,
        "PAYPAL_CURRENCY_CODE": process.env.PAYPAL_CURRENCY_CODE,
        "STRIPE_PRIVATE_KEY": process.env.STRIPE_PRIVATE_KEY,
        "STRIPE_PUBLIC_KEY": process.env.STRIPE_PUBLIC_KEY,
        "STRIPE_PAYMENT_RETURN_URI": process.env.STRIPE_PAYMENT_RETURN_URI,
        "STRIPE_CURRENCY_CODE": process.env.STRIPE_CURRENCY_CODE,
        "REDIS_HOST": process.env.REDIS_HOST,
        "REDIST_PORT": process.env.REDIST_PORT,
      },

      env_staging: {
        "PORT": process.env.PORT,
        "DOMAIN": process.env.DOMAIN,
        "NODE_ENV": "staging",
        "DATABASE_URL": process.env.DATABASE_URL,
        "SESSION_SECRET": process.env.SESSION_SECRET,
        "MYFB_ENDPOINT": process.env.MYFB_ENDPOINT,
        "PEASY_DEAL_ENDPOINT": process.env.PEASY_DEAL_ENDPOINT,
        "PAYPAL_CLIENT_ID": process.env.PAYPAL_CLIENT_ID,
        "PAYPAL_CURRENCY_CODE": process.env.PAYPAL_CURRENCY_CODE,
        "STRIPE_PRIVATE_KEY": process.env.STRIPE_PRIVATE_KEY,
        "STRIPE_PUBLIC_KEY": process.env.STRIPE_PUBLIC_KEY,
        "STRIPE_PAYMENT_RETURN_URI": process.env.STRIPE_PAYMENT_RETURN_URI,
        "STRIPE_CURRENCY_CODE": process.env.STRIPE_CURRENCY_CODE,
        "REDIS_HOST": process.env.REDIS_HOST,
        "REDIST_PORT": process.env.REDIST_PORT,
      },

      env_production: {
        "PORT": process.env.PORT,
        "DOMAIN": process.env.DOMAIN,
        "NODE_ENV": "production",
        "DATABASE_URL": process.env.DATABASE_URL,
        "SESSION_SECRET": process.env.SESSION_SECRET,
        "MYFB_ENDPOINT": process.env.MYFB_ENDPOINT,
        "PEASY_DEAL_ENDPOINT": process.env.PEASY_DEAL_ENDPOINT,
        "PAYPAL_CLIENT_ID": process.env.PAYPAL_CLIENT_ID,
        "PAYPAL_CURRENCY_CODE": process.env.PAYPAL_CURRENCY_CODE,
        "STRIPE_PRIVATE_KEY": process.env.STRIPE_PRIVATE_KEY,
        "STRIPE_PUBLIC_KEY": process.env.STRIPE_PUBLIC_KEY,
        "STRIPE_PAYMENT_RETURN_URI": process.env.STRIPE_PAYMENT_RETURN_URI,
        "STRIPE_CURRENCY_CODE": process.env.STRIPE_CURRENCY_CODE,
        "REDIS_HOST": process.env.REDIS_HOST,
        "REDIST_PORT": process.env.REDIST_PORT,
      },
    },
  ],
}
