const productRichTextClass = [
  'font-poppins text-base text-neutral-800',
  '[&_p]:mb-5',
  '[&_p]:leading-6',
  '[&_p]:font-normal',
  '[&_h1]:text-[22px]',
  '[&_h1]:mt-[18px]',
  '[&_h1]:mb-[14px]',
  '[&_h1]:font-bold',
  '[&_h2]:text-xl',
  '[&_h2]:mt-4',
  '[&_h2]:mb-3',
  '[&_h2]:font-bold',
  '[&_h3]:text-lg',
  '[&_h3]:mt-3.5',
  '[&_h3]:mb-2.5',
  '[&_h3]:font-bold',
  '[&_h4]:text-base',
  '[&_h4]:mt-3',
  '[&_h4]:mb-2',
  '[&_h4]:font-bold',
  '[&_ul]:list-disc',
  '[&_ul]:pl-[17px]',
  '[&_ul]:my-2.5',
  '[&_li]:font-normal',
  '[&_li]:leading-6',
  '[&_hr]:my-2',
  'break-words'
].join(' ');

export { productRichTextClass };
